name: Build and Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest  # ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # the Node.js versions to build on
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }} 
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Lint the project
        run: npm run lint

      - name: Build the project
        run: npm run build

      # Let's test multiple builds which might force a rename
      - name: run build ; audit ; fix ; build
        run: |
          npm run build
          npm list --outdated
          npm audit || true  # ignore failures
          npm audit fix || true
          npm list --outdated
          npm run build
          ls -hal
          ls -hal node_modules
          ls -hal node_modules/homebridge-inkbird-wifi-gateway
